### PR TITLE
Fix S3 public read ACL/policies.

### LINKED ISSUE #31: Module 01 in all languages is broken due to ACL changes in S3 service
All the code using the `public-read` ACL value for S3 buckets is broken because of a change to the S3 service.

We need to implement a similar fix to: https://github.com/pulumi/templates/commit/ed5e07a027b7a3a215d4488631408d513ead6886

### PR DESCRIPTION
**Pull request by jkodroff**
Fixes #31 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jkodroff** [comment]
@mariswa Can you give this a look and let me know if it looks good? If so, I'll add commits to the Python version and remove the draft designation.

**Review by scottslowe — APPROVED** [review]

**Comment by jkodroff** [comment]
@scottslowe Can you also review the Python side? (I'm going to skip Java because we've only run that course once.)

**Review by scottslowe — APPROVED** [review]
LGTM. Note that I didn't run the sample code; I'm assuming you've taken care of that (I didn't see anything that looked glaringly incorrect).

**Comment by scottslowe** [comment]
> @scottslowe Can you also review the Python side? (I'm going to skip Java because we've only run that course once.)

@jkodroff Done!

**Pull request merged**
