### PR TITLE
Fix up fargate exercise

### PR DESCRIPTION
**Pull request by jkodroff**
Clean up the ECS on Fargate exercise to use separate security groups for the ALB and the workload, and make them least priv.

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jkodroff** [comment]
@mariswa

**Comment by jkodroff** [comment]
@jamesbland123 Are you able to approve this?

**Review by NetDevAutomate — APPROVED** [review]

**Review by NetDevAutomate — APPROVED** [review]

**Review by NetDevAutomate — APPROVED** [review]
LGTM

**Review by pablo19sc — APPROVED** [review]
All good!

**Pull request merged**
